### ISSUE TITLE
Let the user rotate pictures which support EXIF [$5]

### ISSUE THREAD

**Issue by oparoz** [owncloud/gallery#236]
Pictures which support EXIF can store rotation information, so we could show rotate buttons and store the new value in the file. The thumbnails would need to be cleared and re-rendered.
##

**Comment by ghost** [comment]
This problem seems to be the same as the old gallery app, i think that was fixed. The problem is the thumbnails is stored as .png and not .jpeg. exif info is not contained in .png format.

I think its possible to look at the fixes made to the old gallery app for a indication of how to solve this problem.

https://github.com/owncloud/apps/issues/1568

**Comment by oparoz** [comment]
Thumbnails and slideshow previews are based off a "max preview" which is created the first time a file is accessed. If the Exif data is correct at that time, then Gallery will show the images with the proper orientation.

So there is no problem anymore, but users want to be able to modify the orientation of pictures they see, in case it's not correct in the JPG itself and that's possible by working directly on the original and re-rendering new thumbnails.

**Comment by metzenseifner** [comment]
@oparoz 

> "max preview" which is created the first time a file is accessed. If the Exif data is correct at that time, then Gallery will show the images with the proper orientation.

I just found your comment while searching for how to the reset gallery for some users. The users who viewed pictures before I uncommented the PHP extension `exif.so` in `/etc/php/php.ini` see incorrectly oriented pictures (ignored Orientation tag in metadata). While _new users_ (post-change) have the correct orientation, the wrong orientation problem persists for older users who viewed the images prior to the change. Any way to reset this for users?

**Comment by oparoz** [comment]
There is no elegant way to reset the previews for a user, because there has been no change to the data itself. Potential solutions:
- re-upload the images
- delete all the thumbnails for those users
- only delete specific thumbnails for those users

**Comment by oparoz** [comment]
This issue was moved to nextcloud/gallery#41
